/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.cegb03.simulacrombc.igu;

import com.cegb03.simulacrombc.logica.Controladora;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author CEGB03
 */
public class Simulacro extends javax.swing.JFrame {
    
    Controladora controladora = new Controladora();
    int numPregunta;

    /**
     * Creates new form Estudiar
     */
    public Simulacro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lNumPregunta = new javax.swing.JLabel();
        btnSig = new javax.swing.JButton();
        btnAnt = new javax.swing.JButton();
        lNumMax = new javax.swing.JLabel();
        pregunta = new javax.swing.JLabel();
        opnA = new javax.swing.JRadioButton();
        opnB = new javax.swing.JRadioButton();
        opnC = new javax.swing.JRadioButton();
        opnD = new javax.swing.JRadioButton();
        btnGrabar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lNumPregunta1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lNumPregunta.setText("1");

        btnSig.setText(">>");
        btnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigActionPerformed(evt);
            }
        });

        btnAnt.setText("<<");
        btnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntActionPerformed(evt);
            }
        });

        lNumMax.setText("/ 20");

        pregunta.setText("aca va la pregunta");

        buttonGroup1.add(opnA);
        opnA.setText("a)");
        opnA.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                opnAStateChanged(evt);
            }
        });
        opnA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opnAActionPerformed(evt);
            }
        });

        buttonGroup1.add(opnB);
        opnB.setText("b)");
        opnB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                opnBStateChanged(evt);
            }
        });

        buttonGroup1.add(opnC);
        opnC.setText("c)");

        buttonGroup1.add(opnD);
        opnD.setText("d)");

        btnGrabar.setText("Comprobar Seleccion");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar Seleccion");
        btnLimpiar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnLimpiarStateChanged(evt);
            }
        });
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lNumPregunta1.setText("1)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addComponent(btnGrabar)
                .addGap(18, 18, 18)
                .addComponent(btnAnt)
                .addGap(24, 24, 24)
                .addComponent(lNumPregunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lNumMax)
                .addGap(26, 26, 26)
                .addComponent(btnSig)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lNumPregunta1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pregunta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opnD)
                            .addComponent(opnC)
                            .addComponent(opnB)
                            .addComponent(opnA))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNumPregunta1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opnA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opnB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opnC)
                .addGap(12, 12, 12)
                .addComponent(opnD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnt)
                    .addComponent(lNumPregunta)
                    .addComponent(lNumMax)
                    .addComponent(btnSig)
                    .addComponent(btnLimpiar)
                    .addComponent(btnGrabar))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntActionPerformed
        int num = Integer.parseInt(lNumPregunta.getText());
        if(num == 1)
        lNumPregunta.setText("20");
        else{
            num--;
            lNumPregunta.setText(String.valueOf(num));
        }
    }//GEN-LAST:event_btnAntActionPerformed

    private void btnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigActionPerformed
        int num = Integer.parseInt(lNumPregunta.getText());
        if(num == 20)
        lNumPregunta.setText("1");
        else{
            num++;
            lNumPregunta.setText(String.valueOf(num));
        }
    }//GEN-LAST:event_btnSigActionPerformed

    private void opnAStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_opnAStateChanged

    }//GEN-LAST:event_opnAStateChanged

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
       String seleccion = "";
        if ( !(opnA.isSelected()) && !(opnB.isSelected()) && !(opnC.isSelected()) && !(opnD.isSelected()) )
             JOptionPane.showMessageDialog(null, "Debes seleccionar una opcion...");
        else if(opnA.isSelected())
           seleccion = "a";
        else if(opnB.isSelected())
            seleccion = "b";
        else if(opnC.isSelected())
            seleccion = "c";
        else if(opnD.isSelected())
            seleccion = "d";
        if( seleccion.equals("a") || seleccion.equals("b") || seleccion.equals("c") || seleccion.equals("d") )
            controladora.controlar(numPregunta, seleccion);
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnLimpiarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnLimpiarStateChanged

    }//GEN-LAST:event_btnLimpiarStateChanged

    private void opnBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_opnBStateChanged
         
    }//GEN-LAST:event_opnBStateChanged

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        opnA.setSelected(false);
        opnB.setSelected(false);
        opnC.setSelected(false);
        opnD.setSelected(false);
        
         jPanel1.setBackground(null);
        
        setTitle("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void opnAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opnAActionPerformed
        jPanel1.setBackground(Color.yellow);
        setTitle("OPCION A SELECCIONADA");
    }//GEN-LAST:event_opnAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnt;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSig;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lNumMax;
    private javax.swing.JLabel lNumPregunta;
    private javax.swing.JLabel lNumPregunta1;
    private javax.swing.JRadioButton opnA;
    private javax.swing.JRadioButton opnB;
    private javax.swing.JRadioButton opnC;
    private javax.swing.JRadioButton opnD;
    private javax.swing.JLabel pregunta;
    // End of variables declaration//GEN-END:variables
}
