INSERT INTO cordoba (`veiculo`, `pregunta`, `opnA`, `opnB`, `opnC`, `opnD`, `opnCorrecta`) VALUES



















('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'c'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'c'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'c'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'c'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'c'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'c'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'c'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'c'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'd'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'c'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'c'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'c'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'c'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'c'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'c'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'c'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'c'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'c'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'c'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'c'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'c'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'b'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'a'),
('B', 'valor_pregunta_2', 'valor_opnA_2', 'valor_opnB_2', 'valor_opnC_2', 'valor_opnD_2', 'a'),
('B', 'valor_pregunta_1', 'valor_opnA_1', 'valor_opnB_1', 'valor_opnC_1', 'valor_opnD_1', 'b'),
('B', 'valor_pregunta_156', 'valor_opnA_156', 'valor_opnB_156', 'valor_opnC_156', 'valor_opnD_156', 'c'),
('B', 'valor_pregunta_156', 'valor_opnA_156', 'valor_opnB_156', 'valor_opnC_156', 'valor_opnD_157', 'c');
