package com.cegb03.anotacionvoley.igu;

import cegb03.anotacionvoley.logica.Equipo;

import javax.swing.*;

/**
 * The type R 5 new.
 *
 * @author ADMIN
 */
public class R5New extends JFrame {
    
   private final Equipo equipoA;
   private final Equipo equipoB;
   private final String[] equipoGrabar = new String[6];
   private final int numSetActual;

    /**
     * Instantiates a new R 5 new.
     *
     * @param numSet  the value of numSet
     * @param equipoA the equipo a
     * @param equipoB the equipo b
     */
    public R5New(int numSet, Equipo equipoA, Equipo equipoB) {
        numSetActual = numSet;
        this.equipoA = equipoA;
        this.equipoB = equipoB;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbNomEquipoNoUsar = new javax.swing.JLabel();
        txtNomEquipo = new javax.swing.JTextField();
        cBoxAB = new javax.swing.JComboBox<>();
        panelSet1 = new javax.swing.JPanel();
        lbNumSet1 = new javax.swing.JLabel();
        lbPos4Set1 = new javax.swing.JLabel();
        lbPos3Set1 = new javax.swing.JLabel();
        lbPos2Set1 = new javax.swing.JLabel();
        txtPos4Set1 = new javax.swing.JTextField();
        txtPos3Set1 = new javax.swing.JTextField();
        txtPos2Set1 = new javax.swing.JTextField();
        lbPos5Set1 = new javax.swing.JLabel();
        lbPos6Set1 = new javax.swing.JLabel();
        lbPos1Set1 = new javax.swing.JLabel();
        txtPos5Set1 = new javax.swing.JTextField();
        txtPos6Set1 = new javax.swing.JTextField();
        txtPos1Set1 = new javax.swing.JTextField();
        panelSet3 = new javax.swing.JPanel();
        lbNumSet3 = new javax.swing.JLabel();
        lbPos4Set3 = new javax.swing.JLabel();
        lbPos3Set3 = new javax.swing.JLabel();
        lbPos2Set3 = new javax.swing.JLabel();
        txtPos4Set3 = new javax.swing.JTextField();
        txtPos3Set3 = new javax.swing.JTextField();
        txtPos2Set3 = new javax.swing.JTextField();
        lbPos5Set3 = new javax.swing.JLabel();
        lbPos6Set3 = new javax.swing.JLabel();
        lbPos1Set3 = new javax.swing.JLabel();
        txtPos5Set3 = new javax.swing.JTextField();
        txtPos6Set3 = new javax.swing.JTextField();
        txtPos1Set3 = new javax.swing.JTextField();
        panelSet2 = new javax.swing.JPanel();
        lbNumSet2 = new javax.swing.JLabel();
        lbPos4Set2 = new javax.swing.JLabel();
        lbPos3Set2 = new javax.swing.JLabel();
        lbPos2Set2 = new javax.swing.JLabel();
        txtPos4Set2 = new javax.swing.JTextField();
        txtPos3Set2 = new javax.swing.JTextField();
        txtPos2Set2 = new javax.swing.JTextField();
        lbPos5Set2 = new javax.swing.JLabel();
        lbPos6Set2 = new javax.swing.JLabel();
        lbPos1Set2 = new javax.swing.JLabel();
        txtPos5Set2 = new javax.swing.JTextField();
        txtPos6Set2 = new javax.swing.JTextField();
        txtPos1Set2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mIGuardar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbNomEquipoNoUsar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lbNomEquipoNoUsar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNomEquipoNoUsar.setText("Equipo");

        txtNomEquipo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNomEquipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNomEquipo.setText("Nombre Equipo");
        txtNomEquipo.setToolTipText("");


        cBoxAB.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cBoxAB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "A", "B" }));
        cBoxAB.setSelectedItem("");
        cBoxAB.setToolTipText("");


        lbNumSet1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNumSet1.setText("1° Set");

        lbPos4Set1.setText("I V");

        lbPos3Set1.setText("I I I");

        lbPos2Set1.setText("I I");

        txtPos4Set1.setHorizontalAlignment(javax.swing.JTextField.CENTER);


        txtPos3Set1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPos2Set1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbPos5Set1.setText("V");

        lbPos6Set1.setText("V I");

        lbPos1Set1.setText("I");

        txtPos5Set1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPos6Set1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPos1Set1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panelSet1Layout = new javax.swing.GroupLayout(panelSet1);
        panelSet1.setLayout(panelSet1Layout);
        panelSet1Layout.setHorizontalGroup(
            panelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSet1Layout.createSequentialGroup()
                .addGroup(panelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSet1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPos4Set1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSet1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(txtPos3Set1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelSet1Layout.createSequentialGroup()
                                .addGroup(panelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPos5Set1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelSet1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lbPos5Set1)))
                                .addGap(62, 62, 62)
                                .addGroup(panelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPos6Set1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPos6Set1))
                                .addGap(56, 56, 56)
                                .addGroup(panelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPos2Set1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPos1Set1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPos1Set1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelSet1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbPos4Set1)
                        .addGap(63, 63, 63)
                        .addGroup(panelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNumSet1)
                            .addGroup(panelSet1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lbPos3Set1)
                                .addGap(72, 72, 72)
                                .addComponent(lbPos2Set1)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelSet1Layout.setVerticalGroup(
            panelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSet1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbNumSet1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPos4Set1)
                    .addComponent(lbPos3Set1)
                    .addComponent(lbPos2Set1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPos4Set1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPos3Set1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPos2Set1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPos5Set1)
                    .addComponent(lbPos6Set1)
                    .addComponent(lbPos1Set1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPos5Set1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPos6Set1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPos1Set1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        lbNumSet3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNumSet3.setText("3° Set");

        lbPos4Set3.setText("I V");

        lbPos3Set3.setText("I I I");

        lbPos2Set3.setText("I I");

        txtPos4Set3.setHorizontalAlignment(javax.swing.JTextField.CENTER);


        txtPos3Set3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPos2Set3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbPos5Set3.setText("V");

        lbPos6Set3.setText("V I");

        lbPos1Set3.setText("I");

        txtPos5Set3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPos6Set3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPos1Set3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panelSet3Layout = new javax.swing.GroupLayout(panelSet3);
        panelSet3.setLayout(panelSet3Layout);
        panelSet3Layout.setHorizontalGroup(
            panelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSet3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSet3Layout.createSequentialGroup()
                        .addGroup(panelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPos4Set3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelSet3Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(txtPos3Set3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelSet3Layout.createSequentialGroup()
                        .addGroup(panelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPos5Set3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelSet3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lbPos5Set3)))
                        .addGap(62, 62, 62)
                        .addGroup(panelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPos6Set3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPos6Set3))
                        .addGroup(panelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSet3Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(panelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPos2Set3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPos1Set3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(24, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSet3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPos1Set3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))))
            .addGroup(panelSet3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbPos4Set3)
                .addGap(63, 63, 63)
                .addGroup(panelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNumSet3)
                    .addGroup(panelSet3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbPos3Set3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbPos2Set3)
                .addGap(40, 40, 40))
        );
        panelSet3Layout.setVerticalGroup(
            panelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSet3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNumSet3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPos4Set3)
                    .addComponent(lbPos3Set3)
                    .addComponent(lbPos2Set3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPos4Set3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPos3Set3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPos2Set3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPos5Set3)
                    .addComponent(lbPos6Set3)
                    .addComponent(lbPos1Set3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPos5Set3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSet3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPos6Set3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPos1Set3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbNumSet2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbNumSet2.setText("2° Set");

        lbPos4Set2.setText("I V");

        lbPos3Set2.setText("I I I");

        lbPos2Set2.setText("I I");

        txtPos4Set2.setHorizontalAlignment(javax.swing.JTextField.CENTER);


        txtPos3Set2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPos2Set2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbPos5Set2.setText("V");

        lbPos6Set2.setText("V I");

        lbPos1Set2.setText("I");

        txtPos5Set2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPos6Set2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPos1Set2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout panelSet2Layout = new javax.swing.GroupLayout(panelSet2);
        panelSet2.setLayout(panelSet2Layout);
        panelSet2Layout.setHorizontalGroup(
            panelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSet2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSet2Layout.createSequentialGroup()
                        .addGroup(panelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPos4Set2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelSet2Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(txtPos3Set2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelSet2Layout.createSequentialGroup()
                        .addGroup(panelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPos5Set2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelSet2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lbPos5Set2)))
                        .addGap(62, 62, 62)
                        .addGroup(panelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPos6Set2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPos6Set2))
                        .addGroup(panelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSet2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(panelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPos2Set2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPos1Set2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(24, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSet2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPos1Set2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))))
            .addGroup(panelSet2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbPos4Set2)
                .addGap(63, 63, 63)
                .addGroup(panelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNumSet2)
                    .addGroup(panelSet2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbPos3Set2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbPos2Set2)
                .addGap(40, 40, 40))
        );
        panelSet2Layout.setVerticalGroup(
            panelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSet2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNumSet2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPos4Set2)
                    .addComponent(lbPos3Set2)
                    .addComponent(lbPos2Set2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPos4Set2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPos3Set2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPos2Set2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPos5Set2)
                    .addComponent(lbPos6Set2)
                    .addComponent(lbPos1Set2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPos5Set2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSet2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPos6Set2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPos1Set2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbNomEquipoNoUsar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(cBoxAB, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSet3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomEquipoNoUsar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBoxAB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSet3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Opciones");

        mIGuardar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        mIGuardar.setText("Grabar Posiciones Set");
        mIGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(mIGuardar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mIGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIGuardarActionPerformed
        String equipoSeleccionado = (String) cBoxAB.getSelectedItem();
        String nombreEquipo = txtNomEquipo.getText();
        boolean grabado = true;

        if(nombreEquipo.isBlank()){
            System.out.println(nombreEquipo);
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del equipo");
            return;
        }            
        
       switch (equipoSeleccionado) {
           case "Select":
               JOptionPane.showMessageDialog(this, "Seleccione un equipo");
               break;
           case "A":
               // Controlar el JTextField correspondiente al equipo A según el set
               equipoA.setNombreEquipo(nombreEquipo); // Nombre del equipo
               // Grabar jugadores
               grabarEquipos();
               // Validar que los JTextField de los jugadores no estén vacíos
               for (int i = 0; i < 5; i++) {
                   String jugador = equipoGrabar[i];
                   if ( jugador.isBlank() ) {
                       JOptionPane.showMessageDialog(this, "Ingrese el número del jugador " + i + " del equipo A");// Sale del método si hay un JTextField vacío
                       grabado = false;
                       //return; // Sale del método si hay un JTextField vacío
                   }
               }
               equipoA.setFormacionOriginal(equipoGrabar);
               // Aquí puedes guardar la información ya que todos los JTextField están llenos
               break;
           case "B":
               // Controlar el JTextField correspondiente al equipo B según el set
               equipoB.setNombreEquipo(nombreEquipo); // Nombre del equipo
               // Grabar jugadores
               grabarEquipos();
               // Validar que los JTextField de los jugadores no estén vacíos
               for (int i = 0; i < 5; i++) {
                   String jugador = equipoGrabar[i];
                   if (jugador == null) {
                       JOptionPane.showMessageDialog(this, "Ingrese el número del jugador " + i + " del equipo B");
                       grabado = false;
                       //return; // Sale del método si hay un JTextField vacío
                   }
               }
               equipoB.setFormacionOriginal(equipoGrabar);
               // Aquí puedes guardar la información ya que todos los JTextField están llenos
               break;
           default:
               break;
       }
        if(grabado){
            JOptionPane.showMessageDialog(this, "Grabado correctamente");
            
        }
    }//GEN-LAST:event_mIGuardarActionPerformed

    private void grabarEquipos(){
        for (int i = 1; i <= 6; i++) {
            switch (numSetActual) {
                case 1 -> {
                    equipoGrabar[0] = txtPos1Set1.getText(); // Nombre del equipo
                    equipoGrabar[1] = txtPos2Set1.getText(); // Nombre del equipo
                    equipoGrabar[2] = txtPos3Set1.getText(); // Nombre del equipo
                    equipoGrabar[3] = txtPos4Set1.getText(); // Nombre del equipo
                    equipoGrabar[4] = txtPos5Set1.getText(); // Nombre del equipo
                    equipoGrabar[5] = txtPos6Set1.getText(); // Nombre del equipo
                }
                case 2 -> {
                    equipoGrabar[0] = txtPos1Set2.getText(); // Nombre del equipo
                    equipoGrabar[1] = txtPos2Set2.getText(); // Nombre del equipo
                    equipoGrabar[2] = txtPos3Set2.getText(); // Nombre del equipo
                    equipoGrabar[3] = txtPos4Set2.getText(); // Nombre del equipo
                    equipoGrabar[4] = txtPos5Set2.getText(); // Nombre del equipo
                    equipoGrabar[5] = txtPos6Set2.getText(); // Nombre del equipo
                }
                case 3 -> {
                    equipoGrabar[0] = txtPos1Set3.getText(); // Nombre del equipo
                    equipoGrabar[1] = txtPos2Set3.getText(); // Nombre del equipo
                    equipoGrabar[2] = txtPos3Set3.getText(); // Nombre del equipo
                    equipoGrabar[3] = txtPos4Set3.getText(); // Nombre del equipo
                    equipoGrabar[4] = txtPos5Set3.getText(); // Nombre del equipo
                    equipoGrabar[5] = txtPos6Set3.getText(); // Nombre del equipo
                }
                default -> throw new AssertionError();
                }
            }
      }

    /**
     * Gets equipo a.
     *
     * @return the equipo a
     */
    public Equipo getEquipoA() {
        return equipoA;
    }

    /**
     * Gets equipo b.
     *
     * @return the equipo b
     */
    public Equipo getEquipoB() {
        return equipoB;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cBoxAB;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbNomEquipoNoUsar;
    private javax.swing.JLabel lbNumSet1;
    private javax.swing.JLabel lbNumSet2;
    private javax.swing.JLabel lbNumSet3;
    private javax.swing.JLabel lbPos1Set1;
    private javax.swing.JLabel lbPos1Set2;
    private javax.swing.JLabel lbPos1Set3;
    private javax.swing.JLabel lbPos2Set1;
    private javax.swing.JLabel lbPos2Set2;
    private javax.swing.JLabel lbPos2Set3;
    private javax.swing.JLabel lbPos3Set1;
    private javax.swing.JLabel lbPos3Set2;
    private javax.swing.JLabel lbPos3Set3;
    private javax.swing.JLabel lbPos4Set1;
    private javax.swing.JLabel lbPos4Set2;
    private javax.swing.JLabel lbPos4Set3;
    private javax.swing.JLabel lbPos5Set1;
    private javax.swing.JLabel lbPos5Set2;
    private javax.swing.JLabel lbPos5Set3;
    private javax.swing.JLabel lbPos6Set1;
    private javax.swing.JLabel lbPos6Set2;
    private javax.swing.JLabel lbPos6Set3;
    private javax.swing.JMenuItem mIGuardar;
    private javax.swing.JPanel panelSet1;
    private javax.swing.JPanel panelSet2;
    private javax.swing.JPanel panelSet3;
    private javax.swing.JTextField txtNomEquipo;
    private javax.swing.JTextField txtPos1Set1;
    private javax.swing.JTextField txtPos1Set2;
    private javax.swing.JTextField txtPos1Set3;
    private javax.swing.JTextField txtPos2Set1;
    private javax.swing.JTextField txtPos2Set2;
    private javax.swing.JTextField txtPos2Set3;
    private javax.swing.JTextField txtPos3Set1;
    private javax.swing.JTextField txtPos3Set2;
    private javax.swing.JTextField txtPos3Set3;
    private javax.swing.JTextField txtPos4Set1;
    private javax.swing.JTextField txtPos4Set2;
    private javax.swing.JTextField txtPos4Set3;
    private javax.swing.JTextField txtPos5Set1;
    private javax.swing.JTextField txtPos5Set2;
    private javax.swing.JTextField txtPos5Set3;
    private javax.swing.JTextField txtPos6Set1;
    private javax.swing.JTextField txtPos6Set2;
    private javax.swing.JTextField txtPos6Set3;
    // End of variables declaration//GEN-END:variables

}
